export { MyOrderScreen } from './myOrder.component';
export { ContactUsScreen } from './contactUs.component';
export { DailyMessageScreen } from './dailyMessage.component';
export { NotificationScreen } from './notification.component';
export { OffersScreen } from './offers.component';
export { OutOfStockScreen } from './outOfStock.component';
export { PayNowScreen } from './payNow.component';
export { StockListScreen } from './stockList.component';
export { ValidityScreen } from './validity.component';
