export enum AppRoute {
  AUTH = 'Auth',
  CUSTOMER_HOME = 'Customer Home',
  CUSTOMER_WALLET = 'Customer Wallet',
  CUSTOMER_ADDRESS = 'Customer Address',
  CUSTOMER_ORDER = 'Customer Order',
  CUSTOMER_NOTIFICATION = 'Customer Notification',
  CUSTOMER_CART = 'Customer Cart',
  CUSTOMER_CONTACT = 'Customer Contact',
  SIGN_IN = 'Sign In',
  OTP = 'Otp',
  SIGN_UP = 'Sign Up',
  FORGET_PASSWORD = 'Forget Passrord',
  SHOP_CUSTOMER = 'Shop Customer',
  SHOP_CUSTOMER_DETAIL = 'Shop Customer Detail',
  ADD_CUSTOMER = 'Add Customer',
  ITEM_CATEGORY = 'Item Category',
  ADD_CATEGORY = 'Add Category',
  ADD_BRAND = 'Add Brand',
  EMPLOYEE = 'Employee',
  ALLITEM = 'All Item',
  PRODUCT_DETAIL = 'Product Detail',
  CART = 'Cart',
  CUSTOMER = 'Customer',
  STOCK = 'Stock',
  BRANDLIST = 'Brand List',
  ITEMLIST = 'Item List',
  ADDEMPLOYEE = 'Add Employee',
  PROFILE = 'Profile',
  CUSTOMER_PROFILE = 'Customer Profile',
  MY_WALLET = 'My Wallet',
  MY_ORDER = 'My Order',
  VALIDITY = 'Validity',
  NOTIFICATION = 'Notification',
  PAY_NOW = 'Pay Now',
  ADD_PRODUCT = 'Add Product',
   ADD_EMPLOYEE = 'Add Employee',
  OUT_OF_STOCK = 'Out of Stock',
  OFFERS = 'Offers',
  DAILY_MESSAGE = 'Daily Message',
  CUSTOMER_LIST = 'Customer List',
  STOCK_LIST = 'Stock List',
  CUSTOMER_ALL_PRODUCT = 'Customer All Product',
  BILL_BOOK = 'Bill Book',
  OFFERS_TAB = 'Offers Tab',
  WISH_LIST = 'Wish List',





  INFORMATION = 'Information',
  HRINFORMATION = 'HrInformation',
  EDUCATION = 'Education',
  EXPERIENCE = 'Experience',
  FRESHER = 'Fresher',
  FRESHERTECH = 'FresherTech',
  COMPANY = 'Company',
  MYJOBS = 'MyJobs',
  JOBDETAIL = 'JobDetail',
  APPLIED = 'Applied',
  APPLIEDDETAIL = 'AppliedDetail',
  RESUME = 'Resume',
  EDITPROFILE = 'EditProfile',
  HOME = 'Home',
  HRHOME = 'HrHome',
  ADDACHIVEMENT = 'AddAchivement',
  ADDEDUCATION = 'AddEducation',
  ADDCERTIFICATE = 'AddCertificate',
  ADDEXPERIENCE = 'AddExperience',
  HRMYJOBS = 'HrMyJobs',
  HRMYJOBDETAIL = 'HrMyJobDetail',
  EDITJOB = 'EditJob',
  CANDIDATE = 'Candidate',
  POSTJOB = 'PostJob',
  POSTJOB2 = 'PostJob2',
  POSTJOB3 = 'PostJob3',
  POSTJOB4 = 'PostJob4',
  POSTJOB5 = 'PostJob5',
  HRPROFILE = 'HrProfile',
  EDITHRPROFILE = 'EditHrProfile',
  PLAN = 'Plan',



  HOME1 = 'Home1',
  HOMEDRAWER = 'HomeDrawer',
  TODO = 'ToDo',
  TODO_IN_PROGRESS = 'ToDo In Progress',
  TODO_DONE = 'ToDo Done',
  TODO_DETAILS = 'ToDo Details',
  CONTACTUS = 'ContactUs',
  CHANGEPASSWORD = 'Changepassword',
  ASK = 'Ask',
  TIMELINE = 'TimeLine',
  LIST = 'List',
  ACCOUNTS = 'Accounts',
  PROFILEEDIT = 'ProfileEdit',
  WALLET = 'Wallet',
  IMAGEUPLOAD = 'ImageUpload',
  LOGOUT = 'Logout',
  LOG_OUT = 'Log Out',
  ASKFREEQUESTION = 'AskFreeQuestion',
  TRANSACTIONHISTORY = 'TransactionHistory',
  MORE = 'More',
  DETAILED = 'Detailed',
  CONTACT = 'CONTACT',
  EXPERTLIST = 'ExpertList',
  SETTING = 'Setting',
  VIEWCONTENT = 'ViewContent',
  ROUTER = 'Router',
  VIDEOHOME = 'VideoHome',
  VIDEO = 'Video',
  HOMEVID = 'HomeVid',
  GOLIVE = 'GoLive',
  SEELIVE = 'SeeLive',




  
  EDITADDRESS = 'EditAddress',
}
